# Generated by Django 5.2.6 on 2025-09-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва кафедри')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код кафедри')),
                ('description', models.TextField(blank=True, verbose_name='Опис кафедри')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва спеціальності')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код спеціальності')),
                ('description', models.TextField(verbose_name='Опис спеціальності')),
                ('coordinator_name', models.CharField(max_length=100, verbose_name="Ім'я координатора набору")),
                ('coordinator_contact', models.TextField(help_text='Email, телефон, кабінет тощо', verbose_name='Контакт координатора набору')),
                ('disciplines', models.TextField(blank=True, help_text='Перерахуйте дисципліни через кому або з нового рядка', verbose_name='Список дисциплін')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='pannel.departments', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Спеціальність',
                'verbose_name_plural': 'Спеціальності',
                'ordering': ['code', 'title'],
            },
        ),
    ]
