# Generated by Django 5.2.6 on 2025-09-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедри'},
        ),
        migrations.RemoveField(
            model_name='departments',
            name='code',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='description',
        ),
        migrations.AddField(
            model_name='departments',
            name='head',
            field=models.CharField(default='(не вказано)', max_length=100, verbose_name='Завідувач кафедри'),
        ),
    ]
