# Generated by Django 5.2.6 on 2025-09-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0002_alter_departments_options_remove_departments_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Завідувач кафедри'),
        ),
    ]
