# Generated by Django 5.2.6 on 2025-09-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0003_alter_departments_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='coordinator_contact',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='coordinator_name',
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('degree', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ступінь')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='pannel.departments', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Викладач',
                'verbose_name_plural': 'Викладачі',
            },
        ),
        migrations.AddField(
            model_name='programs',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_programs', to='pannel.teachers', verbose_name='Координатор набору'),
        ),
    ]
