# Generated by Django 5.2.6 on 2025-09-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0004_remove_programs_coordinator_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
