# Generated by Django 5.2.6 on 2025-09-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannel', '0005_teachers_email_teachers_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис факультету')),
            ],
        ),
        migrations.AlterField(
            model_name='programs',
            name='disciplines',
            field=models.TextField(blank=True, verbose_name='Список дисциплін'),
        ),
    ]
